
#!/usr/bin/env bash

Hostname=$(hostname)
Username=$(whoami)
DateTime=$(date)

source /etc/os-release
OS=$PRETTY_NAME

Uptime=$(uptime -p)
CPU=$(lshw -class processor 2>/dev/null | grep 'product:' | head -1 | awk -F: '{print $2}' | xargs)
RAM=$(free -h | awk '/Mem:/ {print $2}')
Disks=$(lshw -short -class disk 2>/dev/null | awk '{print $2, $3, $4, $5}' | column -t)
Video=$(lshw -C display 2>/dev/null | grep 'product:' | awk -F: '{print $2}' | xargs)

Gateway=$(ip route | awk '/default/ {print $3}')
Host_IP=$(ip route get $GATEWAY | grep -oP 'src \K\S+')
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd, -)

Users=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)
Disk_Space=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 ": " $2}' | paste -sd, -)
Proc_Count=$(ps -e --no-headers | wc -l)
Load_Avg=$(uptime | awk -F'load average:' '{print $2}' | xargs)
Ports=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -u | paste -sd, -)
UFW_Status=$(sudo ufw status | head -n 1)

#-----------------------------------------------------------------------------------------

echo ""
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------

OS: $OS
Uptime: $Uptime
CPU: $CPU
RAM: $RAM
Disk(s): $Disks
Video: $Video
Host Address: $Hosts_IP
Gateway IP: $Gateway
DNS Server: $DNS

System Status
-------------
Users Logged In: $Users
Disk Space: $Disk_Space
Process Count: $Proc_Count
Load Averages: $Load_Avg
Listening Network Ports: $Ports

UFW Status: $UFW_Status
EOF
echo ""











