
#!/usr/bash

Hostname=$(hostname)
Username=$(whoami)
DateTime=$(date)

source /etc/os-release
OS=$PRETTY_NAME

Uptime=$(uptime -p)
CPU=$(lshw -class processor 2>/dev/null | grep 'product:' | head -1 | awk -F: '{print $2}' | xargs)
RAM=$(free -h | awk '/Mem:/ {print $2}')
Disks=$(lshw -short -class disk 2>/dev/null | awk '{print $2, $3, $4, $5}' | column -t)
Video=$(lshw -C display 2>/dev/null | grep 'product:' | awk -F: '{print $2}' | xargs)
Gateway=$(ip r | awk '/default/ {print $3}')
Host_IP=$(ip a | awk '/inet / && !/127.0.0.1/ {print $2}' | cut -d/ -f1 | head -1)
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd, -)

Users=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)
Disk_Space=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}')
Proc_Count=$(ps -e --no-headers | wc -l)
Load_Avg=$(uptime | awk -F'load average:' '{print $2}' | xargs)
Ports=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -u | paste -sd, -)
UFW_Status=$(sudo ufw status | head -n 1)

#-----------------------------------------------------------------------------------------
echo ""
cat <<EOF

System Report for $Hostname generated by $Username, on $DateTime

System Information
------------------
OS: $OS
Uptime: $Uptime
CPU: $CPU
RAM: $RAM
Disk(s):
$Disks
Video: $Video
Host Address: $Host_IP
Gateway IP: $Gateway
DNS Server: $DNS

System Status
-------------
Users Logged In: $Users
Disk Space:
$Disk_Space
Process Count: $Proc_Count
Load Averages: $Load_Avg
Listening Network Ports: $Ports
UFW Status: $UFW_Status

EOF
echo ""


